# docker build and image scan
name: Pull Request CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main", "staging", "develop" ]

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  orca_image_scan:
    name: Orca Image Scan
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: orca-scan-ga-workflow:ci-pr
      ORCA_PROJECT_KEY: "procore-io-platform"
      ORCA_OUTPUT_FILE: "results/polaris-csm-orca-scan-report.json"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: src/gademo
        run: |
          docker build -t $IMAGE_NAME . 

      - name: Run orca shift left security scan on container
        uses: orcasecurity/shiftleft-container-image-action@v1
        id: orca-security-docker-image-scan
        with:
          api_token: ${{ secrets.ORCA_API_TOKEN }}
          project_key: ${{ env.ORCA_PROJECT_KEY }}
          image: ${{ env.IMAGE_NAME }}
          fail_on_severity: high
          output_format: json
          output_file: ${{ env.ORCA_OUTPUT_FILE }}

      - name: Results
        run: |
          if [ -f ${{ env.ORCA_OUTPUT_FILE }} ]; then
            echo "::set-output name=upload::true" 
            echo "Orca scan output file exists:"
            cat ${{ env.ORCA_OUTPUT_FILE }} 
          else
            echo "::set-output name=upload::false"
            echo "Orca scan output file does not exist"
          fi

      - name: Upload Orca Scan Results to Github
        # if: always()
        if: steps.orca-security-docker-image-scan.outputs.upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: orca-scan-results
          path: ${{ env.ORCA_OUTPUT_FILE }}
